"""
Revisar.IA - Enums and Constants
All enumeration types used across the Revisar.IA fiscal audit system
"""
from enum import Enum


class TipologiaProyecto(str, Enum):
    CONSULTORIA_ESTRATEGICA = "CONSULTORIA_ESTRATEGICA"
    CONSULTORIA_MACRO_MERCADO = "CONSULTORIA_MACRO_MERCADO"
    SOFTWARE_SAAS_DESARROLLO = "SOFTWARE_SAAS_DESARROLLO"
    MARKETING_BRANDING = "MARKETING_BRANDING"
    INTRAGRUPO_MANAGEMENT_FEE = "INTRAGRUPO_MANAGEMENT_FEE"
    SERVICIOS_ESG_CUMPLIMIENTO = "SERVICIOS_ESG_CUMPLIMIENTO"
    REESTRUCTURAS = "REESTRUCTURAS"
    OTROS = "OTROS"


class FaseProyecto(str, Enum):
    F0 = "F0"
    F1 = "F1"
    F2 = "F2"
    F3 = "F3"
    F4 = "F4"
    F5 = "F5"
    F6 = "F6"
    F7 = "F7"
    F8 = "F8"
    F9 = "F9"


class EstadoGlobal(str, Enum):
    PENDIENTE = "PENDIENTE"
    APROBADO_ESTRATEGICO = "APROBADO_ESTRATEGICO"
    APROBADO_CONDICIONAL = "APROBADO_CONDICIONAL"
    APROBADO_OPERATIVO = "APROBADO_OPERATIVO"
    RECHAZADO = "RECHAZADO"
    SOLICITAR_AJUSTES = "SOLICITAR_AJUSTES"
    CANCELADO = "CANCELADO"


class TipoRelacionProveedor(str, Enum):
    TERCERO_INDEPENDIENTE = "TERCERO_INDEPENDIENTE"
    PARTE_RELACIONADA_NACIONAL = "PARTE_RELACIONADA_NACIONAL"
    PARTE_RELACIONADA_EXTRANJERA = "PARTE_RELACIONADA_EXTRANJERA"
    INTRAGRUPO = "INTRAGRUPO"


class EstadoFase(str, Enum):
    NO_INICIADA = "NO_INICIADA"
    EN_PROGRESO = "EN_PROGRESO"
    COMPLETADA = "COMPLETADA"
    BLOQUEADA = "BLOQUEADA"
    OMITIDA = "OMITIDA"


class TipoAgente(str, Enum):
    A1_SPONSOR = "A1_SPONSOR"
    A2_PMO = "A2_PMO"
    A3_FISCAL = "A3_FISCAL"
    A4_LEGAL = "A4_LEGAL"
    A5_FINANZAS = "A5_FINANZAS"
    A6_PROVEEDOR = "A6_PROVEEDOR"
    A7_DEFENSA = "A7_DEFENSA"
    SUB_TIPIFICACION = "SUB_TIPIFICACION"
    SUB_MATERIALIDAD = "SUB_MATERIALIDAD"
    SUB_RIESGOS_ESPECIALES = "SUB_RIESGOS_ESPECIALES"


class DecisionAgente(str, Enum):
    APROBAR = "APROBAR"
    APROBAR_CONDICIONES = "APROBAR_CONDICIONES"
    SOLICITAR_AJUSTES = "SOLICITAR_AJUSTES"
    RECHAZAR = "RECHAZAR"
    PENDIENTE = "PENDIENTE"


class TipoDocumento(str, Enum):
    SIB_BEE = "SIB_BEE"
    SOW = "SOW"
    CONTRATO = "CONTRATO"
    ANEXO_TECNICO = "ANEXO_TECNICO"
    INFORME = "INFORME"
    MODELO_PARAMETRICO = "MODELO_PARAMETRICO"
    DASHBOARD = "DASHBOARD"
    MANUAL = "MANUAL"
    MINUTA = "MINUTA"
    CRONOGRAMA = "CRONOGRAMA"
    CFDI = "CFDI"
    COMPROBANTE_PAGO = "COMPROBANTE_PAGO"
    VBC_FISCAL = "VBC_FISCAL"
    VBC_LEGAL = "VBC_LEGAL"
    AUDITORIA_INTERNA = "AUDITORIA_INTERNA"
    EVIDENCIA_EJECUCION = "EVIDENCIA_EJECUCION"
    OTRO = "OTRO"


class AccionAuditLog(str, Enum):
    PROYECTO_CREADO = "PROYECTO_CREADO"
    PROYECTO_ACTUALIZADO = "PROYECTO_ACTUALIZADO"
    FASE_INICIADA = "FASE_INICIADA"
    FASE_COMPLETADA = "FASE_COMPLETADA"
    FASE_BLOQUEADA = "FASE_BLOQUEADA"
    AGENTE_DELIBERACION = "AGENTE_DELIBERACION"
    DOCUMENTO_CARGADO = "DOCUMENTO_CARGADO"
    DOCUMENTO_VALIDADO = "DOCUMENTO_VALIDADO"
    VBC_EMITIDO = "VBC_EMITIDO"
    REVISION_HUMANA_SOLICITADA = "REVISION_HUMANA_SOLICITADA"
    REVISION_HUMANA_COMPLETADA = "REVISION_HUMANA_COMPLETADA"
    RISK_SCORE_CALCULADO = "RISK_SCORE_CALCULADO"
    ESTADO_CAMBIADO = "ESTADO_CAMBIADO"
    ERROR_SISTEMA = "ERROR_SISTEMA"


class StatusPilar(str, Enum):
    CONFORME = "CONFORME"
    CONDICIONADO = "CONDICIONADO"
    NO_CONFORME = "NO_CONFORME"
    EN_RIESGO = "EN_RIESGO"
    FALLA_CRITICA = "FALLA_CRITICA"


class EstadoEvidencia(str, Enum):
    PENDIENTE = "PENDIENTE"
    ENTREGADO = "ENTREGADO"
    INCONSISTENTE = "INCONSISTENTE"


class ResponsableChecklist(str, Enum):
    PROVEEDOR = "PROVEEDOR"
    INTERNO = "INTERNO"
    LEGAL = "LEGAL"
    FISCAL = "FISCAL"
    FINANZAS = "FINANZAS"


class EstadoMaterialidad(str, Enum):
    FALTA = "FALTA"
    OK = "OK"
    INCONSISTENTE = "INCONSISTENTE"
